services:
    todos-api:
        container_name: todos-api
        build:
            context: .
            dockerfile: ./docker/dotnet/Dockerfile
        ports:
            - '8081:8081'
        networks:
            - network

    todos-frontend:
        container_name: todos-frontend
        depends_on:
            - todos-api
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
            args:
                - VITE_API_URL=http://localhost:8081
                - VITE_SERVICE_TYPE=api
        ports:
            - '3000:80'
        networks:
            - network

networks:
    network:
        driver: bridge
